spring:
  application:
    name: gateway-zuul
server:
  port: 7007
#传统的路由转发功能 http://localhost:7007/api-a-url/getUser/1 --> http://localhost:9986/getUser/1
#zuul:
#  routes:
#    api-a-url:
#      path: /api-a-url/**
#      url: http://localhost:9986/
#面向服务的路由转发
#1、添加注册中心 2、添加节点
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: provide-user-service
    api-b:
      path: /api-b/**
      serviceId: provide-user-service2