spring:
  profiles:
    active: master
##使用ip地址的形式定义注册中心的地址
eureka:
  instance:
    prefer-ip-address: true
#禁用自我保护模式
#eureka.server.enable-self-preservation=false

###eureka server 启用安全验证
#security.user.name=tony
#security.user.password=666666
#security.basic.enabled=true

##服务续约任务的调用间隔时间默认为30s
#eureka.instance.lease-renewal-interval-in-seconds=3
###定义服务失效的时间默认是90s
#eureka.instance.lease-expiration-duration-in-seconds=540