server:
  port: 9997
spring:
  application:
    name: cusromer-user-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/

feign:
  url: "http://localhost:8999"
  hystrix:
    enabled: true